### ISSUE TITLE
Getting configuration error on npm start

### ISSUE THREAD

**Issue by nfasate** [seriousben/embeddable-react-widget#92]
Hi, I am getting the following error every time when I do `npm start`, I have change babel loader version to 7.1.5 even though I am getting the same error.

```
> embeddable-react-widget@0.0.1 start /Users/QMCPL/Documents/embeddable-react-widget-master
> webpack-serve --config ./webpack.config.js --mode development --open

ˢᵉʳᵛᵉ Some options were passed which are unsupported:

  --mode

  Please run webpack-serve --help for a list of supported flags.

⬢ wps: An option was passed to WebpackPluginServe that is not valid
ValidationError: "content" is not allowed
    at Object.exports.process (/Users/QMCPL/Documents/embeddable-react-widget-master/node_modules/joi/lib/errors.js:203:19)
    at internals.Object._validateWithOptions (/Users/QMCPL/Documents/embeddable-react-widget-master/node_modules/joi/lib/types/any/index.js:764:31)
    at module.exports.internals.Any.root.validate (/Users/QMCPL/Documents/embeddable-react-widget-master/node_modules/joi/lib/index.js:147:23)
    at validate (/Users/QMCPL/Documents/embeddable-react-widget-master/node_modules/webpack-plugin-serve/lib/validate.js:59:21)
    at new WebpackPluginServe (/Users/QMCPL/Documents/embeddable-react-widget-master/node_modules/webpack-plugin-serve/lib/index.js:50:19)
    at apply (/Users/QMCPL/Documents/embeddable-react-widget-master/node_modules/webpack-serve/lib/plugin.js:65:18)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! embeddable-react-widget@0.0.1 start: `webpack-serve --config ./webpack.config.js --mode development --open`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the embeddable-react-widget@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Awaiting for your replay!

Thanks!

**Comment by seriousben** [comment]
Thanks, I will look at this over the weekend.

**Comment by hstemplewski** [comment]
@seriousben also when you try to `run build` you get error about dependencies: 

```
embeddable-react-widget|master⚡ ⇒ npm run build

> embeddable-react-widget@0.0.1 build /Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget
> NODE_ENV=production webpack-cli --mode production

(node:47300) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Hash: fa0f429fe5d70d1b74ca8e19b812370c18c55122
Version: webpack 4.31.0
Child
    Hash: fa0f429fe5d70d1b74ca
    Time: 1085ms
    Built at: 2019-05-20 12:11:22
     1 asset
    Entrypoint main = widget.js
    [0] ./src/outputs/embeddable-widget.js 3.6 KiB {0} [not cacheable] [built] [failed] [1 error]
    
    ERROR in ./src/outputs/embeddable-widget.js
    Module build failed (from ./node_modules/babel-loader/lib/index.js):
    Error: Cannot find module '@babel/core'
     babel-loader@8 requires Babel 7.x (the package '@babel/core'). If you'd like to use Babel 6.x ('babel-core'), you should install 'babel-loader@7'.
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
        at Function.Module._load (internal/modules/cjs/loader.js:507:25)
        at Module.require (internal/modules/cjs/loader.js:637:17)
        at require (/Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
        at Object.<anonymous> (/Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget/node_modules/babel-loader/lib/index.js:10:11)
        at Module._compile (/Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
        at Module.load (internal/modules/cjs/loader.js:599:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
        at Function.Module._load (internal/modules/cjs/loader.js:530:3)
        at Module.require (internal/modules/cjs/loader.js:637:17)
        at require (/Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
        at loadLoader (/Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget/node_modules/loader-runner/lib/loadLoader.js:18:17)
        at iteratePitchingLoaders (/Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at runLoaders (/Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
        at NormalModule.doBuild (/Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget/node_modules/webpack/lib/NormalModule.js:280:3)
        at NormalModule.build (/Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget/node_modules/webpack/lib/NormalModule.js:427:15)
        at Compilation.buildModule (/Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget/node_modules/webpack/lib/Compilation.js:635:10)
        at moduleFactory.create (/Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget/node_modules/webpack/lib/Compilation.js:1021:12)
        at factory (/Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget/node_modules/webpack/lib/NormalModuleFactory.js:405:6)
        at hooks.afterResolve.callAsync (/Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget/node_modules/webpack/lib/NormalModuleFactory.js:155:13)
        at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
        at AsyncSeriesWaterfallHook.lazyCompileHook (/Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
        at resolver (/Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget/node_modules/webpack/lib/NormalModuleFactory.js:138:29)
        at process.nextTick (/Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget/node_modules/webpack/lib/NormalModuleFactory.js:342:9)
        at process._tickCallback (internal/process/next_tick.js:61:11)
Child
    Hash: 8e19b812370c18c55122
    Time: 1053ms
    Built at: 2019-05-20 12:11:22
     1 asset
    Entrypoint main = bookmarklet.js
    [0] ./src/outputs/bookmarklet.js 3.6 KiB {0} [not cacheable] [built] [failed] [1 error]
    
    ERROR in ./src/outputs/bookmarklet.js
    Module build failed (from ./node_modules/babel-loader/lib/index.js):
    Error: Cannot find module '@babel/core'
     babel-loader@8 requires Babel 7.x (the package '@babel/core'). If you'd like to use Babel 6.x ('babel-core'), you should install 'babel-loader@7'.
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
        at Function.Module._load (internal/modules/cjs/loader.js:507:25)
        at Module.require (internal/modules/cjs/loader.js:637:17)
        at require (/Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
        at Object.<anonymous> (/Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget/node_modules/babel-loader/lib/index.js:10:11)
        at Module._compile (/Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
        at Module.load (internal/modules/cjs/loader.js:599:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
        at Function.Module._load (internal/modules/cjs/loader.js:530:3)
        at Module.require (internal/modules/cjs/loader.js:637:17)
        at require (/Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
        at loadLoader (/Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget/node_modules/loader-runner/lib/loadLoader.js:18:17)
        at iteratePitchingLoaders (/Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at runLoaders (/Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
        at NormalModule.doBuild (/Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget/node_modules/webpack/lib/NormalModule.js:280:3)
        at NormalModule.build (/Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget/node_modules/webpack/lib/NormalModule.js:427:15)
        at Compilation.buildModule (/Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget/node_modules/webpack/lib/Compilation.js:635:10)
        at moduleFactory.create (/Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget/node_modules/webpack/lib/Compilation.js:1021:12)
        at factory (/Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget/node_modules/webpack/lib/NormalModuleFactory.js:405:6)
        at hooks.afterResolve.callAsync (/Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget/node_modules/webpack/lib/NormalModuleFactory.js:155:13)
        at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
        at AsyncSeriesWaterfallHook.lazyCompileHook (/Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
        at resolver (/Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget/node_modules/webpack/lib/NormalModuleFactory.js:138:29)
        at process.nextTick (/Users/hubertstemplewski/Documents/ReactPoland/Clients/embeddable-react-widget/node_modules/webpack/lib/NormalModuleFactory.js:342:9)
        at process._tickCallback (internal/process/next_tick.js:61:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! embeddable-react-widget@0.0.1 build: `NODE_ENV=production webpack-cli --mode production`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the embeddable-react-widget@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hubertstemplewski/.npm/_logs/2019-05-20T10_11_22_959Z-debug.log
```

**Comment by andrody** [comment]
Same Issue (Windows 10)

**Comment by seriousben** [comment]
I found the error. It will require some more time for me to fix it. I will upgrade everything to the latest and will make sure CI/tests catch this in the future.

Sorry for taking so long to figure this out.

**Comment by hsyyid** [comment]
Ah, I duplicated this issue in #97 - sorry about that. I am seeing the same problem.

**Comment by hsyyid** [comment]
For anyone who wants to play with this project while this is being fixed, you can checkout an older commit (it seems that the dependencies are automatically updated in `package.json` if they are considered not breaking, but the CI failed to catch that some of those updates were breaking)

I verified `npm start` works correctly on this commit: 678a0baa6e9a18c4153395c83f697da03f0e27f8

**Comment by hsyyid** [comment]
For anyone who used the commit I referenced, if you plan on using Redux update the React and React-DOM dependencies to `^16.6.0` as Redux uses the [React#memo](https://reactjs.org/blog/2018/10/23/react-v-16-6.html) method.

**Comment by seriousben** [comment]
This should be working now. I've also added more test in the CI pipeline to catch this when testing PRs.
