### ISSUE TITLE
Make sure `npm start` works in tests

### ISSUE THREAD

**Issue by seriousben** [seriousben/embeddable-react-widget#97]

**Comment by hsyyid** [comment]
`npm start` causes errors for me, after cloning the repo and running `npm install` (as in `README`):

This is with `webpack@4.32.2` and `webpack-serve@3.1.0` as specified in `package.json` on Node `v10.8.0` 

```
> webpack-serve --config ./webpack.config.js --mode development --open

ˢᵉʳᵛᵉ Some options were passed which are unsupported:

  --mode

  Please run webpack-serve --help for a list of supported flags.

⬢ wps: An option was passed to WebpackPluginServe that is not valid
ValidationError: "content" is not allowed
    at Object.exports.process (./node_modules/joi/lib/errors.js:203:19)
    at internals.Object._validateWithOptions (./node_modules/joi/lib/types/any/index.js:764:31)
    at module.exports.internals.Any.root.validate (./node_modules/joi/lib/index.js:147:23)
    at validate (./node_modules/webpack-plugin-serve/lib/validate.js:59:21)
    at new WebpackPluginServe (./node_modules/webpack-plugin-serve/lib/index.js:50:19)
    at apply (./node_modules/webpack-serve/lib/plugin.js:65:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! embeddable-react-widget@0.0.1 start: `webpack-serve --config ./webpack.config.js --mode development --open`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the embeddable-react-widget@0.0.1 start script.
```

If I remove the problematic section from the `package.json` (see below) I get a new error.

```json
  "serve": {
    "content": [
      "./dist",
      "./public"
    ]
  },
```

```
ERROR in ./src/outputs/embeddable-widget.js
  Module build failed (from ./node_modules/babel-loader/lib/index.js):
  Error: Cannot find module '@babel/core'
   babel-loader@8 requires Babel 7.x (the package '@babel/core'). If you'd like to use Babel 6.x ('babel-core'), you should install 'babel-loader@7'.
```

If I install `babel-core`, I get another error:

```
ERROR in ./src/outputs/embeddable-widget.js
  Module build failed (from ./node_modules/babel-loader/lib/index.js):
  Error: Plugin/Preset files are not allowed to export objects, only functions. In ./node_modules/babel-preset-stage-2/lib/index.js
```

(I omitted most of the stacktrace so this comment wasn't too long)
